### ISSUE TITLE
[Not a bug] Charts on the disk usage tab

### ISSUE THREAD

**Issue by MPeti1** [darshanparajuli/SimpleSystemMonitorApp#1]
Hi!
On the disk usage tab i think it would be better if the chart's y axis would be speed instead of usage in percent (it's not accurate, because it's not calculated based on response), which would autoscale based on the displayed timeframe's average speed. it would be also a good thing if the active processes tab would show disk r-w speed for processes

**Comment by darshanparajuli** [comment]
Hi @MPeti1 
So in other others, have the disk activity tab show the graph in a similar format as the net activity tab? Yeah, that seems like a good idea. I'll add it as an option.
Disk r/w speed for processes is not accessible for non-rooted devices. For rooted devices, I'll add it given that it's not super expensive operation.

**Comment by MPeti1** [comment]
Thanks :)
