### ISSUE TITLE
Can't see disk activity(internal storage)

### ISSUE THREAD

**Issue by JLoGukA** [darshanparajuli/SimpleSystemMonitorApp#16]
Hello, my device is Xiaomi mi A1(rooted(magisk), android pie) and disk activity graph is always at zero whatever I do with internal memory(I granted SU to the application)
(But even if it's not fixable, your app is great work!))
![Screenshot_20190608-005004](https://user-images.githubusercontent.com/23702864/59135476-b1515b00-8987-11e9-84f3-30620b574bf2.png)
![Screenshot_20190608-004025](https://user-images.githubusercontent.com/23702864/59135487-b910ff80-8987-11e9-8711-114172c7183c.png)

**Comment by Twilite** [comment]
Same issue using my Mi 6 on Android P. I make sure permission is granted. Looking forward to fix it.

**Comment by IshikawaStone** [comment]
Same problem here with redmi note 4 Custom OS Pixel Experience.

**Comment by 5wHN28Dg** [comment]
Same here:(
