### ISSUE TITLE
logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [darshanparajuli/SimpleSystemMonitorApp#3]
Hello Darshan :-) I like this project, do you want me to make a new logo?

**Comment by Arslanshn** [comment]
https://drive.google.com/folderview?id=1I3BhCGwK2ppq70xvrJNm4IMBfmalYlZj

**Comment by darshanparajuli** [comment]
Hey @Arslanshn, I don't think this app needs a new logo atm. Thank you, nevertheless! :)
