### ISSUE TITLE
CPU and Disk Activity empty usage graph (Rooted OnePlus 5T)

### ISSUE THREAD

**Issue by xnutzii** [darshanparajuli/SimpleSystemMonitorApp#5]
hi, my Oneplus 5T is rooted and I cannot read the Usage of my CPU and my Diskusage, even tho I granted SU permission (Magisk Manager). Is there any way to fix this? I am currenty on the Open Beta 10 of my 5T, but this problem is there since the Open Beta 6(?), or since the 8.1 Update. I can read my CPU Usage in apps like Kernel Adiutor and my Disk speed (not sure if it's related to this...) on all Storage benchmarking apps, in Android 7, I tested it, A1 SD Bench with SSM, no problem, was showing the right numbers...Now nothing is showing.

**Comment by Ron998** [comment]
Same.  
ASUS ROG 2, Android 9.
The play Store version (3.6.24) works fine.

**Comment by xnutzii** [comment]
I forgot that I opened this up, nowadays I can read the data with my OnePlus 6T and with 5T.
